// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace DatabaseApplicationML.Model
{
    public class ModelInput
    {
        [ColumnName("Message"), LoadColumn(0)]
        public string Message { get; set; }


        [ColumnName("Characteristic"), LoadColumn(1)]
        public string Characteristic { get; set; }


    }
}
